import AuditAssistant from './AuditAssistant.jsx';
import React,{useState,useEffect} from 'react';
import {Wallet,BrowserProvider,JsonRpcProvider,Contract,formatEther} from 'ethers';
import {ShieldCheck,Box,Users,KeyRound,ScrollText,Activity,LogOut,RefreshCw,ArrowUpRight,CheckCircle2,AlertTriangle,Lock,Search,Download,ChevronRight} from 'lucide-react';

const ZERO='0x0000000000000000000000000000000000000000';
const short=v=>v?`${v.slice(0,8)}…${v.slice(-6)}`:'—';
const same=(a,b)=>a?.toLowerCase()===b?.toLowerCase();
const readable=e=>e?.revert?.name||e?.shortMessage||e?.message||'Operation failed';
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Empty({children}){return <div className="empty"><Box size={28}/><p>{children}</p></div>}
function Pill({ok=true,children}){return <span className={'pill '+(ok?'good':'warn')}>{children}</span>}
function Address({value}){return <code title={value}>{short(value)}</code>}
const views=[['Assets',Box],['Identities',Users],['Access Policies',KeyRound],['Audit Explorer',ScrollText],['Security Results',Activity]];

export default function App(){
 const [config,setConfig]=useState(null),[signer,setSigner]=useState(null),[address,setAddress]=useState(''),[token,setToken]=useState(''),[me,setMe]=useState(null);
 const [tab,setTab]=useState('Assets'),[assets,setAssets]=useState([]),[identities,setIdentities]=useState([]),[policies,setPolicies]=useState([]),[selected,setSelected]=useState(null);
 const [audit,setAudit]=useState(null),[network,setNetwork]=useState(null),[security,setSecurity]=useState(null),[reports,setReports]=useState([]);
 const [busy,setBusy]=useState(''),[notice,setNotice]=useState(null),[search,setSearch]=useState(''),[showMint,setShowMint]=useState(false),[integrity,setIntegrity]=useState(null);
 const [keystore,setKeystore]=useState(''),[password,setPassword]=useState(''),[identityJson,setIdentityJson]=useState(null),[receipt,setReceipt]=useState(null);
 const [destination,setDestination]=useState(''),[grantTo,setGrantTo]=useState(''),[hours,setHours]=useState(24),[recoveryId,setRecoveryId]=useState(''),[recoveryKey,setRecoveryKey]=useState('');
 useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(setConfig).catch(()=>setNotice({error:true,text:'Cannot reach the application. Start the API and verify deployment.'}));},[]);
 const platform=()=>new Contract(config.platform,config.platformAbi,signer);
 const registry=()=>new Contract(config.registry,config.registryAbi,signer);
 async function api(path,options={},authToken=token){const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...(authToken?{Authorization:'Bearer '+authToken}:{}),...options.headers}});if(!r.ok){const b=await r.json().catch(()=>({error:r.statusText}));throw Error(b.error);}return r.json();}
 async function job(label,fn){setBusy(label);setNotice(null);try{await fn();}catch(e){setNotice({error:true,text:readable(e)});}finally{setBusy('');}}
 async function refresh(t=token){if(!t)return;const user=await api('/me',{},t);setMe(user);let result=[],next=1;do{const page=await api('/assets?start='+next,{},t);result.push(...page.items);next=page.next;}while(next);setAssets(result);
  if(user.canCatalogue||user.roleId===0)setIdentities(await api('/identities',{},t));else setIdentities([]);
  setPolicies(await api('/policies',{},t));
  if(user.canAudit){const [a,n,s,r]=await Promise.all([api('/audit',{},t),api('/network',{},t),api('/security',{},t),api('/reports',{},t)]);setAudit(a);setNetwork(n);setSecurity(s);setReports(r);}
 }
 async function connect(kind){await job('Connecting wallet',async()=>{
  let s;if(kind==='extension'){if(!window.ethereum)throw Error('Install a wallet extension or import an encrypted demo wallet.');const p=new BrowserProvider(window.ethereum);await p.send('eth_requestAccounts',[]);const n=await p.getNetwork();if(Number(n.chainId)!==config.chainId){await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:'0x'+config.chainId.toString(16),chainName:'LedgerGuard Local Besu',rpcUrls:[config.rpcUrl],nativeCurrency:{name:'Test Ether',symbol:'ETH',decimals:18}}]});throw Error('Select LedgerGuard Local Besu in your wallet and connect again.');}s=await p.getSigner();}
  else{if(!keystore||!password)throw Error('Choose an encrypted wallet file and enter its password.');s=(await Wallet.fromEncryptedJson(keystore,password)).connect(new JsonRpcProvider(config.rpcUrl,undefined,{cacheTimeout:-1}));setPassword('');setKeystore('');}
  setSigner(s);setAddress(await s.getAddress());setNotice({text:'Wallet connected. Sign in to prove control of your identity.'});
 });}
 async function login(){await job('Verifying identity',async()=>{const challenge=await api('/auth/challenge',{method:'POST',body:JSON.stringify({controller:address})});const signature=await signer.signMessage(challenge.message);const result=await api('/auth/verify',{method:'POST',body:JSON.stringify({id:challenge.id,signature})});setToken(result.token);await refresh(result.token);});}
 async function tx(label,fn){await job(label,async()=>{const transaction=await fn();setNotice({text:'Transaction submitted. Waiting for confirmation.',hash:transaction.hash});const receipt=await transaction.wait();if(receipt.status!==1)throw Error('Transaction reverted');setNotice({text:label+' confirmed',hash:receipt.hash});if(token)await refresh();});}
 async function logout(){try{if(token)await api('/auth/logout',{method:'POST'});}finally{setToken('');setMe(null);setSigner(null);setAddress('');setAssets([]);setSelected(null);setSecurity(null);setAudit(null);setReports([]);setIdentityJson(null);setPassword('');setKeystore('');}}
 useEffect(()=>{if(!window.ethereum)return;const changed=()=>{logout();};window.ethereum.on?.('accountsChanged',changed);window.ethereum.on?.('chainChanged',changed);return()=>{window.ethereum.removeListener?.('accountsChanged',changed);window.ethereum.removeListener?.('chainChanged',changed);};},[token]);
 async function mint(e){e.preventDefault();const form=new FormData(e.currentTarget);await job('Encrypting file and minting asset',async()=>{const file=form.get('file');if(!file?.size)throw Error('Select a file');if(file.size>2097152)throw Error('Maximum file size is 2 MiB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(const b of bytes)binary+=String.fromCharCode(b);
  const staged=await api('/files',{method:'POST',body:JSON.stringify({name:file.name,code:form.get('code'),description:form.get('description'),mime:file.type||'application/octet-stream',data:btoa(binary)})});
  const t=await platform().mint(staged.codeHash,staged.contentHash,staged.uri);setNotice({text:'Mint submitted. Waiting for confirmation.',hash:t.hash});await t.wait();setShowMint(false);await refresh();setNotice({text:'Asset minted. Allocate it to an identity to finish registration.',hash:t.hash});});}
 async function download(a){await job('Checking file permission',async()=>{const r=await fetch(`/api/assets/${a.id}/content`,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error((await r.json()).error);const blob=await r.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=a.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice({text:'File integrity verified and download authorised.'});});}
 const current=assets.find(a=>a.id===selected),isAdmin=me?.roleId===1;
 const allowedViews=views.filter(([name])=>name==='Assets'||name==='Access Policies'||(name==='Identities'&&(me?.canCatalogue||me?.roleId===0))||((name==='Audit Explorer'||name==='Security Results')&&me?.canAudit));
 const myIdentity=identities.find(i=>same(i.identity,me?.identity));
 const heading=tab==='Assets'?'Digital assets':tab==='Identities'?'Identity directory':tab==='Access Policies'?'Access policies':tab==='Audit Explorer'?'Audit explorer':tab==='Account'?'Your identity':'Security results';
 return <div className={me?'shell':'welcome-shell'}>
  {me&&<aside className="sidebar"><div className="brand"><ShieldCheck/><span>LedgerGuard<small>IDENTITY & ASSET CONTROL</small></span></div><div className="workspace-label">WORKSPACE</div><nav>{allowedViews.map(([name,Icon])=><button key={name} className={tab===name?'active':''} onClick={()=>{setTab(name);setSearch('');setSelected(null);}}><Icon size={19}/>{name}</button>)}</nav><div className="sidebar-bottom"><div className="network-label">Private Besu network<small>Chain {config?.chainId}</small></div><button onClick={()=>{setTab('Account');setIdentityJson(null);}}><span className="avatar">{me.role[0]}</span><span>{me.role}<small>{short(me.identity)}</small></span></button><button onClick={logout}><LogOut size={16}/>Sign out</button></div></aside>}
  <main className={me?'workspace':'welcome'}>
   {!me?<><div className="brand dark"><ShieldCheck/><span>LedgerGuard<small>IDENTITY & ASSET CONTROL</small></span></div><div className="login-grid"><section><p className="eyebrow">SECURE WORKSPACE</p><h1>Identity you control.<br/>Ownership you can verify.</h1><p className="intro">Manage digital assets, enforce access permissions and inspect the evidence behind every change.</p><div className="login-facts"><span><KeyRound/>Signed identity</span><span><Box/>Controlled assets</span><span><ScrollText/>Verifiable history</span></div><p className="muted">SIH 26125 · Local prototype</p></section><section className="login-panel"><h2>{signer?'Prove your identity':'Connect your wallet'}</h2>{!config?<p>Connecting to the application…</p>:signer?<><p>Controller</p><code className="full-address">{address}</code><button className="primary wide" disabled={!!busy} onClick={login}>Sign in with a signed challenge <ArrowUpRight size={17}/></button><details><summary>New identity or guardian recovery</summary><p className="muted">New identities start without organisational permissions. An Admin must assign a role.</p><button disabled={!!busy} onClick={()=>tx('Identity registration',()=>registry().register(ZERO))}>Register this wallet as an identity</button><Field label="Identity requiring recovery"><input value={recoveryId} onChange={e=>setRecoveryId(e.target.value)} placeholder="0x…"/></Field><Field label="New controller address"><input value={recoveryKey} onChange={e=>setRecoveryKey(e.target.value)} placeholder="0x…"/></Field><button disabled={!!busy} onClick={()=>tx('Recovery request',()=>registry().requestRecovery(recoveryId,recoveryKey))}>Request recovery</button><button disabled={!!busy} onClick={()=>tx('Recovery completion',()=>registry().completeRecovery(recoveryId))}>Complete after 24 hours</button></details><button className="text-button" onClick={logout}>Disconnect wallet</button></>:<><button className="primary wide" disabled={!!busy} onClick={()=>connect('extension')}>Use wallet extension <ArrowUpRight size={17}/></button><div className="divider">or use an encrypted local wallet</div><Field label="Encrypted wallet JSON"><input type="file" accept=".json" onChange={async e=>setKeystore(await e.target.files[0]?.text()||'')}/></Field><Field label="Wallet password"><input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)}/></Field><button className="wide" disabled={!!busy||!keystore} onClick={()=>connect('file')}>Unlock locally</button><p className="muted small"><Lock size={13}/> Your decrypted key stays in this browser’s memory and is cleared on disconnect.</p></>}</section></div></>:<>
    <header className="topbar"><span>Workspace <ChevronRight size={15}/> {tab}</span><button disabled={!!busy} onClick={()=>job('Refreshing',()=>refresh())}><RefreshCw size={16}/> Refresh</button></header>
    <div className="page-title"><div><p className="eyebrow">{tab==='Audit Explorer'?'ON-CHAIN EVIDENCE':tab==='Security Results'?'VALIDATION & MONITORING':'ENTERPRISE WORKSPACE'}</p><h1>{heading}</h1></div>{tab==='Assets'&&isAdmin&&<button className="primary" disabled={!!busy||me.paused} onClick={()=>setShowMint(!showMint)}>{showMint?'Close form':'+ Register asset'}</button>}</div>
    {me.paused&&<div className="banner warning"><AlertTriangle size={18}/> Asset operations and file access are paused. Identity governance remains available.</div>}
    {me.roleId===0&&<div className="banner">Your identity is registered. Ask an Admin to assign an organisational role.</div>}
    {tab==='Assets'&&<>
     <div className="stats"><div><span>Visible assets</span><strong>{assets.length}</strong></div><div><span>Allocated</span><strong>{assets.filter(a=>a.allocated&&!a.retired).length}</strong></div><div><span>Awaiting allocation</span><strong>{assets.filter(a=>!a.allocated).length}</strong></div><div><span>Permission status</span><strong className="text-stat">{me.paused?'Paused':'Enforced on-chain'}</strong></div></div>
     {showMint&&<form className="panel mint-form" onSubmit={mint}><div><h2>Register a digital asset</h2><p>Upload an encrypted document reference, then sign its NFT registration.</p></div><Field label="Unique asset code"><input name="code" required maxLength={80} pattern="[A-Za-z0-9._-]+" placeholder="BEL-DOC-001"/></Field><Field label="Description"><input name="description" maxLength={1000} placeholder="Purpose or document description"/></Field><Field label="File · maximum 2 MiB"><input name="file" type="file" required/></Field><button className="primary" disabled={!!busy}>Encrypt & mint NFT</button></form>}
     <div className="asset-layout"><section className="panel"><div className="panel-top"><h2>Asset register</h2><label className="search"><Search size={16}/><input aria-label="Search assets" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search assets"/></label></div>{assets.length?<div className="table-scroll"><table><thead><tr><th>Asset</th><th>Owner identity</th><th>Status</th><th></th></tr></thead><tbody>{assets.filter(a=>`${a.name} ${a.code}`.toLowerCase().includes(search.toLowerCase())).map(a=><tr key={a.id} className={selected===a.id?'selected':''}><td><button className="asset-name" onClick={()=>{setSelected(a.id);setIntegrity(null);setDestination('');}}><span className="asset-icon"><Box size={20}/></span><span>{a.name}<small>{a.code} · Token #{a.id}</small></span></button></td><td><Address value={a.allocated?a.owner:null}/></td><td><Pill ok={a.allocated&&!a.retired}>{a.retired?'Retired':a.allocated?'Allocated':'Unallocated'}</Pill></td><td><button aria-label={'Open '+a.name} onClick={()=>{setSelected(a.id);setIntegrity(null);}}><ChevronRight size={16}/></button></td></tr>)}</tbody></table></div>:<Empty>No assets yet. An Admin can register the first document.</Empty>}</section>
     {current&&<section className="panel detail"><div className="panel-top"><h2>Asset #{current.id}</h2><button onClick={()=>setSelected(null)} aria-label="Close asset detail">×</button></div><h3>{current.name}</h3><p>{current.description||'No description provided.'}</p><Field label="Content fingerprint"><code className="hash">{current.contentHash}</code></Field><Field label="Owner DID"><code className="hash">{current.ownerDid||'Awaiting Admin allocation'}</code></Field><Pill ok={current.metadataVerified}>{current.metadataVerified?'References match chain':'References unavailable or mismatched'}</Pill><button className="wide" disabled={!!busy||!current.canRead} onClick={()=>download(current)}><Download size={16}/> Download verified file</button>
      {!current.retired&&(isAdmin||me.canTransfer)&&<div className="detail-section"><h3>{current.allocated?'Transfer ownership':'Allocate to identity'}</h3><select aria-label="New owner" value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Select active identity</option>{identities.filter(i=>i.active&&!i.suspended&&i.roleId>0&&!same(i.identity,current.owner)).map(i=><option key={i.identity} value={i.identity}>{i.role} · {short(i.identity)}</option>)}</select><button className="primary wide" disabled={!!busy||!destination||me.paused||(!current.allocated&&!isAdmin)} onClick={()=>tx(current.allocated?'Ownership transfer':'Asset allocation',()=>current.allocated?platform().transferFrom(current.owner,destination,current.id):platform().allocate(current.id,destination))}>{current.allocated?'Sign transfer':'Sign allocation'}</button><p className="muted small">Transfers invalidate existing delegated file access.</p></div>}
      {isAdmin&&!current.retired&&<div className="detail-section"><h3>Document access</h3><select aria-label="Access identity" value={grantTo} onChange={e=>setGrantTo(e.target.value)}><option value="">Select identity</option>{identities.filter(i=>i.active&&!i.suspended&&i.roleId>0).map(i=><option key={i.identity} value={i.identity}>{i.role} · {short(i.identity)}</option>)}</select><Field label="Access duration in hours"><input type="number" min="1" max="8760" value={hours} onChange={e=>setHours(e.target.value)}/></Field><div className="button-row"><button disabled={!!busy||!grantTo||Number(hours)<1||Number(hours)>8760} onClick={()=>tx('Access grant',()=>platform().setAccess(current.id,grantTo,Math.floor(Date.now()/1000)+Number(hours)*3600))}>Grant</button><button disabled={!!busy||!grantTo} onClick={()=>tx('Access revocation',()=>platform().setAccess(current.id,grantTo,0))}>Revoke</button></div><button className="danger text-button" disabled={!!busy||me.paused} onClick={()=>{if(confirm('Retire this asset permanently? Its history will remain.'))tx('Asset retirement',()=>platform().retire(current.id));}}>Retire asset</button></div>}
      {me.canAudit&&<div className="detail-section"><button disabled={!!busy} onClick={()=>job('Checking cached ownership',async()=>setIntegrity(await api(`/assets/${current.id}/integrity`)))}>Compare database with chain</button>{integrity&&<p><Pill ok={integrity.status==='MATCH'}>{integrity.status}</Pill></p>}{integrity&&<small className="hash">Chain: {integrity.chainOwner}<br/>Cache: {integrity.cachedOwner||'Not indexed'}</small>}{isAdmin&&<button className="text-button" disabled={!!busy} onClick={()=>job('Rebuilding cache',async()=>{await api(`/assets/${current.id}/cache`,{method:'POST'});setIntegrity(await api(`/assets/${current.id}/integrity`));})}>Rebuild verified cache</button>}</div>}
     </section>}</div>
    </>}
    {tab==='Identities'&&<section className="panel"><div className="panel-top"><h2>Registered identities</h2><span className="muted">{identities.length} records</span></div><div className="table-scroll"><table><thead><tr><th>Identity</th><th>Controller</th><th>Role</th><th>Status</th><th>Governance</th></tr></thead><tbody>{identities.map(i=><tr key={i.identity}><td><button className="text-button" onClick={()=>job('Resolving identity',async()=>setIdentityJson(await api('/did/'+i.identity)))}><Address value={i.identity}/></button><small>Version {i.version}</small></td><td><Address value={i.controller}/></td><td>{isAdmin&&i.active?<select aria-label={'Role for '+i.identity} value={i.roleId} disabled={!!busy} onChange={e=>{const value=Number(e.target.value);if(confirm(`Change ${short(i.identity)} to ${['Unassigned','Admin','Manager','Auditor','User'][value]}?`))tx('Role update',()=>platform().setRole(i.identity,value));}}>{['Unassigned','Admin','Manager','Auditor','User'].map((r,n)=><option value={n} key={r}>{r}</option>)}</select>:i.role}</td><td><Pill ok={i.active&&!i.suspended}>{!i.active?'Deactivated':i.suspended?'Suspended':'Active'}</Pill></td><td>{isAdmin&&i.active&&i.roleId!==1&&<button disabled={!!busy} onClick={()=>tx('Suspension update',()=>platform().setSuspended(i.identity,!i.suspended))}>{i.suspended?'Restore':'Suspend'}</button>}</td></tr>)}</tbody></table></div></section>}
    {tab==='Access Policies'&&<><p className="section-intro">Administrators control minting, initial allocation and governance. Configurable permissions below are enforced by the asset contract.</p><section className="panel"><table><thead><tr><th>Role</th><th>Transfer assets</th><th>Inspect audit</th><th>Browse catalogue</th></tr></thead><tbody>{policies.map(p=><tr key={p.roleId}><td><strong>{p.role}</strong></td>{[1,2,4].map(bit=><td key={bit}><input type="checkbox" aria-label={`${p.role} permission ${bit}`} checked={!!(p.bits&bit)} disabled={!isAdmin||p.roleId===1||!!busy} onChange={()=>tx('Policy update',()=>platform().setPolicy(p.roleId,p.bits^bit))}/></td>)}</tr>)}</tbody></table></section><p className="muted">Catalogue visibility does not grant document downloads. Downloads require ownership, Admin status or a current explicit access grant.</p>{isAdmin&&<section className="panel governance"><div><h2>Emergency pause</h2><p>Stop minting, allocation, transfers and document retrieval while investigating an incident.</p></div><button className={me.paused?'primary':'danger'} disabled={!!busy} onClick={()=>{if(confirm(me.paused?'Resume asset operations?':'Pause all asset operations and document access?'))tx('Emergency pause update',()=>platform().setPaused(!me.paused));}}>{me.paused?'Resume operations':'Pause operations'}</button></section>}</>}
    {tab==='Audit Explorer'&&<>{network&&<><div className="stats"><div><span>Latest block</span><strong>{network.block}</strong></div><div><span>Network</span><strong className="text-stat">Besu · QBFT</strong></div><div><span>Reachable validators</span><strong>{network.validators.filter(n=>n.online).length} / {network.validators.length||'—'}</strong></div></div><section className="panel chain-panel"><h2>Current ledger head</h2><div className="chain-evidence"><div><span>Parent block hash</span><code>{network.parentHash}</code></div><ChevronRight/><div><span>Block #{network.block}</span><code>{network.hash}</code></div></div><div className="node-row">{network.validators.map(n=><span key={n.node}><Pill ok={n.online}>Validator {n.node}: {n.online?'block '+n.block:'unreachable'}</Pill></span>)}</div></section></>}
    <section className="panel receipt-form"><form onSubmit={e=>{e.preventDefault();const hash=new FormData(e.currentTarget).get('hash');job('Reading transaction receipt',async()=>setReceipt(await api('/transactions/'+hash)));}}><Field label="Inspect a transaction, including failed transactions"><input name="hash" required pattern="0x[a-fA-F0-9]{64}" placeholder="0x… transaction hash"/></Field><button disabled={!!busy}>Inspect receipt</button></form>{receipt&&<pre>{JSON.stringify(receipt,null,2)}</pre>}</section><section className="panel"><div className="panel-top"><div><h2>Contract events</h2><small>Read directly from the blockchain</small></div><label className="search"><Search size={16}/><input aria-label="Filter events" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Event, token or identity"/></label></div><div className="timeline">{audit?.events.filter(e=>JSON.stringify(e).toLowerCase().includes(search.toLowerCase())).map(e=><details key={e.transactionHash+e.index}><summary><span className="timeline-mark"/><span><strong>{e.event}</strong><small>{e.kind} contract · Block {e.blockNumber}</small></span><Address value={e.transactionHash}/></summary><pre>{JSON.stringify(e,null,2)}</pre></details>)}</div>{audit?.previousTo!==null&&<button className="load-more" disabled={!!busy} onClick={()=>job('Loading earlier events',async()=>{const older=await api('/audit?to='+audit.previousTo);setAudit({...older,events:[...audit.events,...older.events]});})}>Load earlier blocks</button>}</section></>}
    {tab==='Security Results'&&me?.canAudit&&<><AuditAssistant key={token} api={api}/><div className="stats"><div><span>Log integrity</span><strong className="text-stat">{security?.missingAnchors.length?'Checkpoint mismatch':security?.verification.valid?'Chain consistent':'Mismatch detected'}</strong></div><div><span>Anchored checkpoints</span><strong>{security?.anchorMatches.length||0}</strong></div><div><span>Experiment reports</span><strong>{reports.length}</strong></div></div><section className="panel governance"><div><h2>Anchor security evidence</h2><p>Commit the current log fingerprint to the blockchain. Later edits or removal can be checked against this checkpoint.</p><code className="hash">{security?.verification.head}</code>{!!security?.missingAnchors.length&&<p className="danger">Previously anchored log entries are missing.</p>}</div><button disabled={!!busy||!security?.verification.valid||!security?.verification.count} onClick={()=>tx('Security evidence anchor',()=>platform().anchorEvidence('0x'+security.verification.head,'security-log'))}>Sign checkpoint</button></section>
      {reports.length?reports.map(r=><section className="panel report" key={r.id}><div className="panel-top"><div><h2>{r.report.title}</h2><small>{new Date(r.created_at).toLocaleString()} · Imported test-run evidence</small></div><Pill ok={r.report.tests.every(t=>t.passed)}>{r.report.tests.filter(t=>t.passed).length}/{r.report.tests.length} passed</Pill></div><details><summary>Environment and methodology</summary><pre>{JSON.stringify(r.report.environment,null,2)}</pre></details><table><thead><tr><th>Test</th><th>Result</th><th>Time</th></tr></thead><tbody>{r.report.tests.map((t,i)=><tr key={i}><td>{t.name}<small>{t.details}</small></td><td><Pill ok={t.passed}>{t.passed?'Passed':'Failed'}</Pill></td><td>{t.durationMs.toFixed(0)} ms</td></tr>)}</tbody></table><button disabled={!!busy} onClick={()=>tx('Experiment evidence anchor',()=>platform().anchorEvidence('0x'+r.digest,'experiment-report'))}>Anchor report fingerprint</button></section>):<section className="panel"><Empty>No experiment reports yet. Run the supplied security experiment suite, then refresh.</Empty></section>}
      <section className="panel"><div className="panel-top"><h2>Application security log</h2><small>Off-chain events · latest 200</small></div><div className="table-scroll"><table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Outcome</th></tr></thead><tbody>{security?.logs.map(r=><tr key={r.id}><td>{new Date(r.at).toLocaleTimeString()}</td><td>{r.action}<small>{r.details}</small></td><td><Address value={r.actor}/></td><td><Pill ok={r.outcome==='ALLOWED'}>{r.outcome}</Pill></td></tr>)}</tbody></table></div></section></>}
    {tab==='Account'&&<section className="panel account"><h2>Stable identity, replaceable controller</h2><Field label="Your identity"><code className="hash">did:sih:{config.chainId}:{me.identity.toLowerCase()}</code></Field><Field label="Current controller"><code>{address}</code></Field><button disabled={!!busy} onClick={()=>job('Resolving identity',async()=>setIdentityJson(await api('/did/'+me.identity)))}>Resolve DID document</button><div className="detail-section"><h3>Rotate your signing key</h3><p>Ownership and roles stay attached to your identity. Your existing session will expire. Keep the new wallet available before signing.</p><form onSubmit={e=>{e.preventDefault();const next=new FormData(e.currentTarget).get('controller');if(confirm('Rotate to this controller? You must control its private key to sign in again.'))tx('Controller rotation',()=>registry().rotate(next));}}><Field label="New controller address"><input name="controller" required placeholder="0x…"/></Field><button disabled={!!busy}>Sign key rotation</button></form></div><div className="detail-section"><h3>Recovery guardian</h3><code className="hash">{me.guardian===ZERO?'No guardian configured':me.guardian}</code>{me.recovery?.readyAt>0&&<p className="danger">Recovery pending for {short(me.recovery.controller)}. Eligible after {new Date(me.recovery.readyAt*1000).toLocaleString()}.</p>}<p>A guardian can request a controller change after a 24-hour delay. You can cancel a pending request.</p><form onSubmit={e=>{e.preventDefault();const guardian=new FormData(e.currentTarget).get('guardian');tx('Guardian update',()=>registry().setGuardian(guardian));}}><Field label="Guardian address"><input name="guardian" placeholder="0x…" required/></Field><button disabled={!!busy}>Set guardian</button></form><button className="text-button" disabled={!!busy} onClick={()=>tx('Recovery cancellation',()=>registry().cancelRecovery())}>Cancel pending recovery</button></div><div className="detail-section"><h3>Deactivate identity</h3><p>Permanent. Administrators must first transfer governance and demote their role. Historical ownership remains recorded.</p><button className="danger" disabled={!!busy||isAdmin} onClick={()=>{if(confirm('Permanently deactivate this identity?'))tx('Identity deactivation',()=>registry().deactivate());}}>Deactivate identity</button></div></section>}
    {identityJson&&<section className="panel json-panel"><div className="panel-top"><h2>DID resolution</h2><button onClick={()=>setIdentityJson(null)}>Close</button></div><pre>{JSON.stringify(identityJson,null,2)}</pre></section>}
   </>}
   {(busy||notice)&&<div className={'notification '+(notice?.error?'error':'')} role="status">{busy?<span className="spinner"/>:notice?.error?<AlertTriangle size={19}/>:<CheckCircle2 size={19}/>}<div><strong>{busy||notice?.text}</strong>{busy&&notice?.text&&<small>{notice.text}</small>}{notice?.hash&&<code>{notice.hash}</code>}</div>{!busy&&<button aria-label="Dismiss notification" onClick={()=>setNotice(null)}>×</button>}</div>}
  </main>
 </div>;
}
